name: 🐞 Bug Report
description: Report a reproducible issue with the GUI web base image
title: "[Bug]: "
labels: [bug]
assignees:
  - Aandree5
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us reproduce and fix it.

  - type: input
    id: description
    attributes:
      label: Description of the Issue
      description: Brief description of the issue
      placeholder: "App crashes when launched via browser"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Include exact steps, commands, or URLs
      placeholder: |
        1. Build image with tag v1.1.1
        2. Run container with `docker run -p 5005:5005 ...`
        3. Open browser and click "Start"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "App should launch and display GUI in browser"

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "Browser shows 502 Bad Gateway"

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Docker 24.0.2 on Ubuntu 22.04, Chrome 117"

  - type: textarea
    id: suggestion
    attributes:
      label: Possible Fix / Suggestion
      placeholder: "Maybe related to missing X11 socket or audio forwarding"
