name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
