name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com

            MAJOR=${{ steps.release.outputs.major }}
            MINOR=${{ steps.release.outputs.minor }}
            TAG=${{ steps.release.outputs.tag_name }}

            # Delete old tags if they exist
            git tag -d v$MAJOR || true
            git tag -d v$MAJOR.$MINOR || true
            git push origin :v$MAJOR || true
            git push origin :v$MAJOR.$MINOR || true

            # Create new tags pointing to the current release
            git tag -a v$MAJOR -m "Release v$MAJOR"
            git tag -a v$MAJOR.$MINOR -m "Release v$MAJOR.$MINOR"
            git push origin v$MAJOR
            git push origin v$MAJOR.$MINOR
